### ISSUE TITLE
Enable Solaris support for go-zfs

### ISSUE THREAD

**Issue by amitkris** [mistifyio/go-zfs#39]
Hi,

This is part of a larger effort to develop a native port of Docker on Solaris.
go-zfs is great but has the following issues on Solaris:
1. On Solaris zfs get doesn't support the -t option (only zfs list does).
2. zpool doesn't support -t.
3. zfs get doesn't support -r|-d after all
i.e. the invocation zfs get all -d <depth> will error out.

As a part of coming up with a PR for this fix I investigated whether this should be resolved by creating a separate invocation for Solaris which would call zfs list but I propose a generic change due to performance improvements that it will bring to go-zfs.
Please see the issue titled "switch from zfs get to zfs list calls for better performance" (#40)

I propose to submit a commom PR to fix both these issues.

**Comment by mmlb** [comment]
Fixed by #41, though I don't have a Solaris box so if any breakages occur /shrug
