### ISSUE TITLE
dataset.GetProperty(key) always returns 'VALUE'

### ISSUE THREAD

**Issue by simt2** [mistifyio/go-zfs#49]
dataset.GetProperty uses the first line of `zfs get` without any switches.

**Comment by mikudeko** [comment]
#50 fix

**Comment by mmlb** [comment]
#50 has been merged

**Comment by Myzel394** [comment]
For the future people coming over this, here's what to do:

1. Install v3 of this library using `go get github.com/mistifyio/go-zfs/v3`
2. Remove the existing go-zfs line, it probably includes something like `github.com/mistifyio/go-zfs v2.1.1+incompatible`
3. Update your imports to `"github.com/mistifyio/go-zfs/v3"`
